name: C/C++ CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
        
    steps:
    - name: Remove broken LLVM repository
      run: sudo rm -f /etc/apt/sources.list.d/llvm-toolchain-noble.list

    - name: Update system packages
      run: sudo apt-get update

    - uses: actions/checkout@v2
    - name: Run C++ Linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: 'file'
        tidy-checks: ''
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

    - name: Fail fast if linting fails
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cache: false

    - name: cmake
      run: cmake .
    - name: make all targets
      run: make all

    - name: UT for BtsApplication
      run: make BtsApplicationUT 

    - name: run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: UT for COMMON
      run: make COMMON_UT

    - name: UT for UeApplication
      run: make UeApplicationUT

    - name: Next Steps
      run: echo "Add your next steps here"

